require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DropsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Drop. As you add validations to Drop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DropsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all drops as @drops" do
      drop = Drop.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:drops)).to eq([drop])
    end
  end

  describe "GET show" do
    it "assigns the requested drop as @drop" do
      drop = Drop.create! valid_attributes
      get :show, {:id => drop.to_param}, valid_session
      expect(assigns(:drop)).to eq(drop)
    end
  end

  describe "GET new" do
    it "assigns a new drop as @drop" do
      get :new, {}, valid_session
      expect(assigns(:drop)).to be_a_new(Drop)
    end
  end

  describe "GET edit" do
    it "assigns the requested drop as @drop" do
      drop = Drop.create! valid_attributes
      get :edit, {:id => drop.to_param}, valid_session
      expect(assigns(:drop)).to eq(drop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Drop" do
        expect {
          post :create, {:drop => valid_attributes}, valid_session
        }.to change(Drop, :count).by(1)
      end

      it "assigns a newly created drop as @drop" do
        post :create, {:drop => valid_attributes}, valid_session
        expect(assigns(:drop)).to be_a(Drop)
        expect(assigns(:drop)).to be_persisted
      end

      it "redirects to the created drop" do
        post :create, {:drop => valid_attributes}, valid_session
        expect(response).to redirect_to(Drop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drop as @drop" do
        post :create, {:drop => invalid_attributes}, valid_session
        expect(assigns(:drop)).to be_a_new(Drop)
      end

      it "re-renders the 'new' template" do
        post :create, {:drop => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested drop" do
        drop = Drop.create! valid_attributes
        put :update, {:id => drop.to_param, :drop => new_attributes}, valid_session
        drop.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested drop as @drop" do
        drop = Drop.create! valid_attributes
        put :update, {:id => drop.to_param, :drop => valid_attributes}, valid_session
        expect(assigns(:drop)).to eq(drop)
      end

      it "redirects to the drop" do
        drop = Drop.create! valid_attributes
        put :update, {:id => drop.to_param, :drop => valid_attributes}, valid_session
        expect(response).to redirect_to(drop)
      end
    end

    describe "with invalid params" do
      it "assigns the drop as @drop" do
        drop = Drop.create! valid_attributes
        put :update, {:id => drop.to_param, :drop => invalid_attributes}, valid_session
        expect(assigns(:drop)).to eq(drop)
      end

      it "re-renders the 'edit' template" do
        drop = Drop.create! valid_attributes
        put :update, {:id => drop.to_param, :drop => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drop" do
      drop = Drop.create! valid_attributes
      expect {
        delete :destroy, {:id => drop.to_param}, valid_session
      }.to change(Drop, :count).by(-1)
    end

    it "redirects to the drops list" do
      drop = Drop.create! valid_attributes
      delete :destroy, {:id => drop.to_param}, valid_session
      expect(response).to redirect_to(drops_url)
    end
  end

end
